library(here)
library(ape)
library(phangorn)
library(Matrix)
library(castor)
library(gridExtra)
library(purrr)
library(phytools)
library(parallel)
library(adephylo)
library(reshape2)
library(stringr)


cs = read.tree("/Users/kopp/Desktop/beast-data-sim-1/beast-data-sim-1-8/consensus-8.tree")
tt = read.tree("/Users/kopp/Desktop/beast-data-sim-1/beast-data-sim-1-8/tree-sim-1-8.tree")

par(mfrow=c(1,2))
plot(tt, cex=0.7)
plot(cs, direction = "leftwards", cex=0.7)
