library(here)
library(tidyverse)
library(tibble)
library(ape)
library(phytools)
library(adephylo)
library(castor)
# Bantu ---------------------------------------------------------------------------------------

bantu_group_a <- c(
  "Fefe_Grassfields",
  "Mungaka_Grassfields",
  "Bamun_Grassfields",
  "Kom_Grassfields",
  "Oku_Grassfields",
  "Aghem_Grassfields",
  "Njen_Grassfields",
  "Moghamo_Grassfields",
  "Tiv_Tivoid"
)

bantu_group_b <- c(
  "*D20B_Vamba_1919",
  "*D304_Homa_1919",
  "*D305_Nyanga-li",
  "*D308_Bodo2",
  "*D308_Ebodo",
  "A11_Londo",
  "A121_Mbonge",
  "A122_Bakundu",
  "A141_Lefo",
  "A151_Nkongho",
  "A15A_Mbuu",
  "A15B_Mienge_NW_Manenguba",
  "A15C_Akossi",
  "A15C_Elung_Central_Manenguba",
  "A15C_Mkaa",
  "A15_Manenguba",
  "A22_Bakweri",
  "A24_Duala",
  "A27_Malimba",
  "A31_Bubi",
  "A32C_Batanga",
  "A33a_Yasa",
  "A34_Benga",
  "A41_Barombi-Kang",
  "A42_Abo",
  "A43a_Basaa",
  "A44_Tunen",
  "A45_Nyokon",
  "A462_Yambeta",
  "A46_Nomaande",
  "A51_Bafia_maja",
  "A53_Bafia_rikpa",
  "A54_Tibea",
  "A601_Tuki",
  "A61_Ngoro-Asom",
  "A61_Ngoro-Bisoo",
  "A61_Ngoro-lunda",
  "A621_Nubaca",
  "A622_Nugunu",
  "A62A_Nuasue",
  "A62A_Nukalonge",
  "A62B_Mmala",
  "A62C_Libie",
  "A63_Mangisa",
  "A71_Eton",
  "A72a_Ewondo",
  "A74a_Bulu",
  "A75a_Fang_Bitam",
  "A75a_Fang_Medouneu",
  "A75a_Fang_Minvoul",
  "A803_Shiwa",
  "A81_Kwasio",
  "A832_Bekol",
  "A83_Mekaa",
  "A841_Badwe",
  "A84_Njem",
  "A85b_Bekwil_Makokou",
  "A85b_Bekwil_Mv",
  "A86c_Mpiemo",
  "A87_Bomwali",
  "A91_Kwakum",
  "A93_Kako",
  "B11F_Enenga",
  "B11a_Mpongwe",
  "B11b_Orungu",
  "B11c_Galwa",
  "B11d_Dyumba",
  "B201_Ndasa",
  "B202_Sigu",
  "B203_Samaye",
  "B204_Ndambomo_Li",
  "B204_Ndambomo_Massoukou",
  "B204_Ndambomo_Mbadi",
  "B21_Seki",
  "B22E_Mwesa",
  "B22a_Kele",
  "B22b_Koya",
  "B22b_Ngom",
  "B23_Mbangwe",
  "B24_Wumbvu",
  "B251_Shake",
  "B252_Mahongwe",
  "B25_Kota",
  "B301_Viya",
  "B302_Himba",
  "B304_Pinzi",
  "B305_Vove",
  "B31_Tsogo",
  "B32_Kande",
  "B404_Ngubi",
  "B41_Shira",
  "B42_Sangu_Mb",
  "B42_Sangu_Mi",
  "B43_Punu",
  "B44_Lumbu",
  "B501_Wanzi_E",
  "B501_Wanzi_Mo",
  "B503_Vili",
  "B51_Duma",
  "B51_Duma_La",
  "B52_Nzebi",
  "B53_Tsaangi_Poungi",
  "B601_Lempini",
  "B602_Kaningi_Nord",
  "B602_Kaningi_Sud",
  "B62_Mbaama",
  "B63_Ndumu",
  "B701_Atsitsege",
  "B71aIb_Teke_Ibali_Congo",
  "B71aLe_Teke_Leconi",
  "B71a_Teke_Dj",
  "B71a_Teke_Os",
  "B77b_Fumu",
  "B78_Wuumu",
  "B81_Tiene",
  "B82_Buma",
  "B84_Mbunda",
  "B85_Yanzi",
  "B85d_Nsongo",
  "B85e_Mput",
  "B861_Ngul",
  "B862_Lwel",
  "B863_Pindi",
  "B864_Ngong",
  "B865_Nzadi",
  "B86_Dinga",
  "B86_Dzing",
  "Bile_Jarawan",
  "Bwazza_Jarawan",
  "C101_Babole_Dz",
  "C101_Babole_Ep",
  "C101_Babole_Ma",
  "C104_Aka",
  "C105_Mbenga",
  "C141_Bonyala",
  "C142_Mondongo",
  "C15_Bongili",
  "C21_Ngare",
  "C22_Akwa",
  "C24_Koyo",
  "C25A_Bunji",
  "C25B_Olee",
  "C25C_Ondinga",
  "C25E_Eboyi",
  "C25_Mboshi",
  "C302_Bolondo",
  "C322_Zamba",
  "C323_Mpama",
  "C32_Bobangi",
  "C34_Sakata",
  "C36d_Lingala",
  "C36g_Monyongo",
  "C36g_Mosange",
  "C37_Ebudza",
  "C401_Babati_1919",
  "C401_Pakabete",
  "C412_Libobi",
  "C41_Ngombe",
  "C42_Ebwela",
  "C43A_Baati",
  "C44_Bwa",
  "C52_Soko",
  "C52_Soko_1919",
  "C54_Turumba_1919",
  "C55_Lokele",
  "C61E_Konda",
  "C61_Mongo",
  "C71_Tetela",
  "C76_Ombo",
  "C81_Dengese",
  "C83_Bushong",
  "C85_Wongo",
  "D11_Mbole",
  "D12_Lengola",
  "D13_Metoko",
  "D14_Enya",
  "D201_Liko",
  "D211_Kango",
  "D21_Baali",
  "D23_Kibira-Kumu_1919",
  "D24_Songola",
  "D25_Lega",
  "D28_Holoholo",
  "D311_Bila",
  "D313_Mbuttu_1919",
  "D32_Bira",
  "D32_Bira_Bunia",
  "D331_Bvanuma",
  "D333_Ndaaka",
  "D334_Mbo",
  "D33_Nyali",
  "D43_Nyanga",
  "D55_Buyu",
  "Duguri_Jarawan",
  "E46_Sonjo",
  "E51_Kikuyu",
  "E52_Embu",
  "E52_Mbeere",
  "E531_Muthambi",
  "E531_Mwimbi",
  "E53_Igoji",
  "E53_Imenti",
  "E53_Meru",
  "E53_Meruimenti",
  "E53_Merutig",
  "E53_Miutini",
  "E53_Tigania",
  "E541_Chuka",
  "E54_Tharaka",
  "E55_Kamba",
  "E55_Kamba_Kitu",
  "E55_Kamba_Mach",
  "E56_Daiso",
  "E621B_Machame",
  "E621C_Siha",
  "E621D_Kibosho",
  "E622A_Kimochi",
  "E622C_Lema",
  "E622C_Mamba",
  "E622C_Vunjo",
  "E623A_Kiseri",
  "E623D_Keni",
  "E623_Mkuu",
  "E64_Kahe",
  "E65_Gweno",
  "E701_Elwana",
  "E71A_Upper_Pokomo",
  "E72a_Giryama",
  "E73_Digo",
  "E74a_Dawida",
  "E74a_Tuveta",
  "F12_Bende",
  "F21_Ntuzu",
  "F21_Sukuma",
  "F22_Nyamwezi",
  "F23_Sumbwa",
  "F24_Kimbu",
  "F25_Bungu",
  "F31_Nyiramba",
  "F32_Nyaturucha",
  "F32_Nyaturuwil",
  "F33_Langi",
  "G11_Gogo",
  "G12_Kagulu",
  "G22A_North_Pare",
  "G22B_South_Pare",
  "G22_Asu",
  "G23_Sambaa",
  "G24_Bondei",
  "G31_Zigua",
  "G32_Doe",
  "G32_Kwere",
  "G33_Zaramo",
  "G34_Nguungulu",
  "G35_Luguru",
  "G36_Kami",
  "G37_Kutu",
  "G39_Saghala",
  "G401_Mwani",
  "G412_Mwiini",
  "G41_Bajuni",
  "G42_Swahili",
  "G42a_Amu",
  "G42d_Unguja",
  "G43_Kae",
  "G44D_Maore",
  "G44a_Ngazija",
  "G44b_Ndzwani",
  "G51_Pogoro",
  "G52_Ndamba",
  "G61_Sangu",
  "G62_Hehe",
  "G63_Bena",
  "G64_Pangwa",
  "G65_Kinga",
  "G66_Wanji",
  "H111_Hangala",
  "H11_Beembe",
  "H12_Civili_Congo",
  "H131_Kisundi_Congo_Kimongo_1988",
  "H13_Kikunyi_1989",
  "H16_Cilinji",
  "H16_Cimbala",
  "H16_Cizobe",
  "H16_Kikongo",
  "H16_Kimbata_Ngidinga",
  "H16_Kimbeko",
  "H16a_Kisikongo_2013",
  "H16a_Kisolongo_DRC_2012",
  "H16b_Kindibu_2013",
  "H16c_Kiyombe_DRC_1982",
  "H16c_Yombe",
  "H16d_Ciwoyo_DRC_2012",
  "H16f_Laadi",
  "H16g_Kimpangu_2012",
  "H16g_Ntandu",
  "H16h_Kinkanu_2012",
  "H21a_Kimbundu",
  "H31_Yaka",
  "H321_Soonde",
  "H32_Suku",
  "H41_Mbala",
  "H42_Hunganna",
  "JD53_Shi",
  "JD62_Rundi",
  "JD64_Shubi",
  "JD65_Hangaza",
  "JD66_Kiha",
  "JD67_Kivinza",
  "JE11_Runyoro",
  "JE12_Rutooro",
  "JE13_Runyankore",
  "JE14_Rukiga",
  "JE15_Luganda",
  "JE16_Lusoga",
  "JE17_Gwere",
  "JE21_Runyambo",
  "JE22_Haya",
  "JE23_Zinza",
  "JE24_Kerebe",
  "JE25_Jita",
  "JE25_Kilegi",
  "JE25_Mkwaya",
  "JE31_Lumasaaba",
  "JE31c_Bukusu",
  "JE32_Luyia",
  "JE34_Samialugwe",
  "JE401_Ngoreme",
  "JE402_Ikizu",
  "JE403_Suba",
  "JE404_Shasi",
  "JE41_Maragoli",
  "JE42_Gusii",
  "JE43_Kuria",
  "JE43_Kuria_Mago",
  "JE43_Kuria_Tari",
  "JE44_Zanaki",
  "JE45_Nata",
  "K11_Ciokwe",
  "K14_Lwena",
  "K15_Mbunda",
  "K21_Lozi",
  "K31_Luyana",
  "K332_Rumanyo",
  "K33_Kwangali",
  "Kulung_Jarawan",
  "L11_Pende",
  "L12b_Holu",
  "L13_Kwese",
  "L221_Lwalwa",
  "L23_Songe",
  "L31a_Luba-Kasai",
  "L32_Kanyok",
  "L33_Luba-Shaba",
  "L34_Hemba",
  "L35_Sanga",
  "L41_Kaonde",
  "L51_Salampasu",
  "L52_Lunda",
  "L53_Runda",
  "L62_Nkoya",
  "M11_Pimbwe",
  "M12_Lungwa",
  "M13_Fipa",
  "M14_Rungu",
  "M15_Mambwe",
  "M21_Ndali",
  "M21_Wanda",
  "M22_Namwanga",
  "M23_Nyiha",
  "M24_Malila",
  "M25_Safwa",
  "M28_Lambya",
  "M31_Nyakyusa",
  "M41_Taabwa",
  "M42_Bemba",
  "M52_Lala",
  "M54_Lamba",
  "M61_Lenje",
  "M62_Soli",
  "M64_Tonga",
  "Mbula_Jarawan",
  "N11_Manda",
  "N12_Ngoni",
  "N13_Matengo",
  "N14_Mpoto",
  "N21_Tumbuka_Malawi",
  "N31_Chewa",
  "N42_Kunda",
  "P11_Ndengeleko",
  "P12_Rufiji",
  "P13_Matumbi",
  "P14_Ngindo",
  "P15_Mbunga",
  "P21_Yao",
  "P22_Mwera",
  "P23_Simakonde",
  "P25_Mabia",
  "P31G_Ikorovere",
  "P31_Emakhua",
  "R11_Umbundu",
  "R21_Kwanyama",
  "R22_Ndonga",
  "R31_Herero",
  "S11_Shona",
  "S16_Kalanga",
  "S21_Venda",
  "S311_Shekgalagari",
  "S31_Tswana",
  "S41_Xhosa",
  "S42_Zulu",
  "S44_Ndebele",
  "S51_Tshwa",
  "S53_Tsonga",
  "Zaambo_Jarawan"
)

bantu_group_c <- c(
  "Duguri_Jarawan",
  "Kulung_Jarawan",
  "Bile_Jarawan",
  "Zaambo_Jarawan",
  "Bwazza_Jarawan",
  "Mbula_Jarawan",
  "A54_Tibea",
  "A51_Bafia_maja",
  "A53_Bafia_rikpa",
  "A31_Bubi",
  "A45_Nyokon",
  "A44_Tunen",
  "A46_Nomaande",
  "A462_Yambeta",
  "A601_Tuki",
  "A622_Nugunu",
  "A62B_Mmala",
  "A62C_Libie",
  "A62A_Nuasue",
  "A62A_Nukalonge",
  "A621_Nubaca",
  "A24_Duala",
  "A27_Malimba",
  "A33a_Yasa",
  "A32C_Batanga",
  "A34_Benga",
  "A22_Bakweri",
  "A122_Bakundu",
  "A11_Londo",
  "A121_Mbonge",
  "A141_Lefo",
  "A15C_Akossi",
  "A15C_Mkaa",
  "A15C_Elung_Central_Manenguba",
  "A151_Nkongho",
  "A15A_Mbuu",
  "A15_Manenguba",
  "A15B_Mienge_NW_Manenguba",
  "A43a_Basaa",
  "A41_Barombi-Kang",
  "A42_Abo",
  "A61_Ngoro-lunda",
  "A61_Ngoro-Asom",
  "A61_Ngoro-Bisoo",
  "A63_Mangisa",
  "A71_Eton",
  "A72a_Ewondo",
  "A74a_Bulu",
  "A75a_Fang_Bitam",
  "A75a_Fang_Minvoul",
  "A75a_Fang_Medouneu"
)

bantu_group_d <- c(
  "E55_Kamba_Mach",
  "E623_Mkuu",
  "G61_Sangu",
  "E51_Kikuyu",
  "P15_Mbunga",
  "G12_Kagulu",
  "JE15_Luganda",
  "F25_Bungu",
  "M52_Lala",
  "E53_Imenti",
  "M11_Pimbwe",
  "E56_Daiso",
  "D21_Baali",
  "JD62_Rundi",
  "G66_Wanji",
  "E54_Tharaka",
  "E621B_Machame",
  "G33_Zaramo",
  "K21_Lozi",
  "*D308_Bodo2",
  "E71A_Upper_Pokomo",
  "JE25_Mkwaya",
  "G42_Swahili",
  "S44_Ndebele",
  "JE14_Rukiga",
  "E55_Kamba_Kitu",
  "E53_Meruimenti",
  "E73_Digo",
  "H321_Soonde",
  "E622C_Vunjo",
  "E621D_Kibosho",
  "M25_Safwa",
  "P22_Mwera",
  "E65_Gweno",
  "L11_Pende",
  "E55_Kamba",
  "C44_Bwa",
  "M21_Wanda",
  "H16g_Ntandu",
  "JE25_Jita",
  "JE401_Ngoreme",
  "G22_Asu",
  "L13_Kwese",
  "M41_Taabwa",
  "JE31_Lumasaaba",
  "H21a_Kimbundu",
  "F21_Ntuzu",
  "M14_Rungu",
  "*D304_Homa_1919",
  "P25_Mabia",
  "L221_Lwalwa",
  "G44a_Ngazija",
  "P21_Yao",
  "JE31c_Bukusu",
  "M28_Lambya",
  "F12_Bende",
  "M15_Mambwe",
  "JD67_Kivinza",
  "JE44_Zanaki",
  "E53_Tigania",
  "M24_Malila",
  "JE41_Maragoli",
  "F24_Kimbu",
  "E622A_Kimochi",
  "JE22_Haya",
  "G44b_Ndzwani",
  "S16_Kalanga",
  "JE17_Gwere",
  "E53_Meru",
  "JE404_Shasi",
  "S51_Tshwa",
  "L12b_Holu",
  "M23_Nyiha",
  "G32_Kwere",
  "G63_Bena",
  "JE43_Kuria_Tari",
  "M61_Lenje",
  "JE43_Kuria_Mago",
  "S41_Xhosa",
  "G65_Kinga",
  "G24_Bondei",
  "G43_Kae",
  "G51_Pogoro",
  "S53_Tsonga",
  "P12_Rufiji",
  "E53_Merutig",
  "JE13_Runyankore",
  "JE16_Lusoga",
  "F31_Nyiramba",
  "G401_Mwani",
  "G42d_Unguja",
  "JE24_Kerebe",
  "JE402_Ikizu",
  "E623A_Kiseri",
  "JE43_Kuria",
  "N42_Kunda",
  "F32_Nyaturuwil",
  "*D308_Ebodo",
  "E46_Sonjo",
  "E52_Embu",
  "M22_Namwanga",
  "P14_Ngindo",
  "G37_Kutu",
  "G31_Zigua",
  "JE11_Runyoro",
  "JE25_Kilegi",
  "E64_Kahe",
  "E531_Mwimbi",
  "N21_Tumbuka_Malawi",
  "G44D_Maore",
  "G412_Mwiini",
  "N13_Matengo",
  "G42a_Amu",
  "E53_Miutini",
  "F23_Sumbwa",
  "L51_Salampasu",
  "M12_Lungwa",
  "JE45_Nata",
  "JE32_Luyia",
  "S311_Shekgalagari",
  "E74a_Dawida",
  "G22A_North_Pare",
  "G34_Nguungulu",
  "G41_Bajuni",
  "G39_Saghala",
  "N31_Chewa",
  "E72a_Giryama",
  "P11_Ndengeleko",
  "M13_Fipa",
  "JD53_Shi",
  "JE34_Samialugwe",
  "JE403_Suba",
  "E623D_Keni",
  "E531_Muthambi",
  "JE23_Zinza",
  "E74a_Tuveta",
  "S31_Tswana",
  "F22_Nyamwezi",
  "D201_Liko",
  "G22B_South_Pare",
  "JD65_Hangaza",
  "P13_Matumbi",
  "H41_Mbala",
  "F21_Sukuma",
  "M64_Tonga",
  "E622C_Mamba",
  "M42_Bemba",
  "G52_Ndamba",
  "M31_Nyakyusa",
  "S21_Venda",
  "F33_Langi",
  "G32_Doe",
  "E53_Igoji",
  "JE12_Rutooro",
  "E541_Chuka",
  "G23_Sambaa",
  "G36_Kami",
  "S42_Zulu",
  "E621C_Siha",
  "JE21_Runyambo",
  "E701_Elwana",
  "E52_Mbeere",
  "N11_Manda",
  "G35_Luguru",
  "M21_Ndali",
  "E622C_Lema",
  "JE42_Gusii",
  "F32_Nyaturucha",
  "P23_Simakonde",
  "M62_Soli",
  "N14_Mpoto",
  "P31G_Ikorovere",
  "G11_Gogo",
  "N12_Ngoni",
  "G64_Pangwa",
  "G62_Hehe",
  "M54_Lamba",
  "JD64_Shubi",
  "S11_Shona",
  "JD66_Kiha",
  "P31_Emakhua"
)

bantu_group_a <- tibble(family = "Bantu", calibration = "a", tip = bantu_group_a, s=6.975)
bantu_group_b <- tibble(family = "Bantu", calibration = "b", tip = bantu_group_b, s=4.458)
bantu_group_c <- tibble(family = "Bantu", calibration = "c", tip = bantu_group_c, s=3.234)
bantu_group_d <- tibble(family = "Bantu", calibration = "d", tip = bantu_group_d, s=2.498)


# Bantu subsample ---------------------------------------------------------------------------------------

bantusubsample_group_a <- c("Kom_Grassfields" ,
                            "Mungaka_Grassfields" ,
                            "Fefe_Grassfields" ,
                            "Tiv_Tivoid" ,
                            "Bamun_Grassfields" ,
                            "Oku_Grassfields" )


bantusubsample_group_b <- c("B11a_Mpongwe" ,
                            "A62C_Libie" ,
                            "Bwazza_Jarawan" ,
                            "A31_Bubi" ,
                            "B201_Ndasa" ,
                            "B11F_Enenga" ,
                            "A53_Bafia_rikpa" ,
                            "B203_Samaye" ,
                            "B32_Kande" ,
                            "A61_Ngoro-lunda" ,
                            "A87_Bomwali" ,
                            "B22b_Koya" ,
                            "A622_Nugunu" ,
                            "B305_Vove" ,
                            "A62B_Mmala" ,
                            "A151_Nkongho" ,
                            "B23_Mbangwe" ,
                            "Kulung_Jarawan" ,
                            "A27_Malimba" ,
                            "A74a_Bulu" ,
                            "D211_Kango" ,
                            "C41_Ngombe" ,
                            "C37_Ebudza" ,
                            "D32_Bira" ,
                            "C401_Babati_1919" ,
                            "C21_Ngare" ,
                            "C104_Aka" ,
                            "C83_Bushong" ,
                            "C61E_Konda" ,
                            "C101_Babole_Dz" ,
                            "C85_Wongo" ,
                            "*D308_Ebodo" ,
                            "C15_Bongili" ,
                            "C52_Soko" ,
                            "D313_Mbuttu_1919" ,
                            "D11_Mbole" ,
                            "*D308_Bodo2" ,
                            "C25B_Olee" ,
                            "C52_Soko_1919" ,
                            "C25_Mboshi" ,
                            "B44_Lumbu" ,
                            "B85e_Mput" ,
                            "B85_Yanzi" ,
                            "B701_Atsitsege" ,
                            "B71aIb_Teke_Ibali_Congo" ,
                            "B601_Lempini" ,
                            "H16d_Ciwoyo_DRC_2012" ,
                            "H131_Kisundi_Congo_Kimongo_1988" ,
                            "H16f_Laadi" ,
                            "H16c_Kiyombe_DRC_1982" ,
                            "B51_Duma" ,
                            "H16b_Kindibu_2013" ,
                            "B865_Nzadi" ,
                            "B861_Ngul" ,
                            "B41_Shira" ,
                            "H42_Hunganna" ,
                            "H31_Yaka" ,
                            "H16g_Kimpangu_2012" ,
                            "B42_Sangu_Mb" ,
                            "B71a_Teke_Dj" ,
                            "L32_Kanyok" ,
                            "D201_Liko" ,
                            "S42_Zulu" ,
                            "F22_Nyamwezi" ,
                            "G12_Kagulu" ,
                            "F23_Sumbwa" ,
                            "E46_Sonjo" ,
                            "F24_Kimbu" ,
                            "G22A_North_Pare" ,
                            "JE43_Kuria_Mago" ,
                            "K15_Mbunda" ,
                            "JE15_Luganda" ,
                            "JE11_Runyoro" ,
                            "P21_Yao" ,
                            "M21_Ndali" ,
                            "M42_Bemba" ,
                            "G52_Ndamba" ,
                            "G22_Asu" ,
                            "M54_Lamba" ,
                            "G36_Kami" ,
                            "L35_Sanga" ,
                            "L13_Kwese" ,
                            "R21_Kwanyama" ,
                            "H41_Mbala" ,
                            "R11_Umbundu" ,
                            "R22_Ndonga" ,
                            "L34_Hemba" ,
                            "K14_Lwena" ,
                            "L23_Songe" ,
                            "R31_Herero" ,
                            "K31_Luyana" ,
                            "L53_Runda" ,
                            "L33_Luba-Shaba" ,
                            "H21a_Kimbundu" ,
                            "L51_Salampasu" ,
                            "K11_Ciokwe" ,
                            "L41_Kaonde" ,
                            "L12b_Holu" ,
                            "L11_Pende")


bantusubsample_group_c <-c("A151_Nkongho",
                           "A27_Malimba",
                           "A31_Bubi",
                           "A53_Bafia_rikpa",
                           "A61_Ngoro-lunda",
                           "A622_Nugunu",
                           "A62B_Mmala",
                           "A62C_Libie",
                           "A74a_Bulu",
                           "Bwazza_Jarawan",
                           "Kulung_Jarawan")


bantusubsample_group_d <- c("D201_Liko",
                            "S42_Zulu",
                            "F22_Nyamwezi",
                            "G12_Kagulu",
                            "F23_Sumbwa",
                            "E46_Sonjo",
                            "F24_Kimbu",
                            "G22A_North_Pare",
                            "JE43_Kuria_Mago",
                            "JE15_Luganda",
                            "JE11_Runyoro",
                            "P21_Yao",
                            "M21_Ndali",
                            "M42_Bemba",
                            "G52_Ndamba",
                            "G22_Asu",
                            "M54_Lamba",
                            "G36_Kami",
                            "L13_Kwese",
                            "H41_Mbala",
                            "H21a_Kimbundu",
                            "L51_Salampasu",
                            "L12b_Holu",
                            "L11_Pende")


bantusubsample_group_a <- tibble(family = "Bantu_subset", calibration = "a", tip = bantusubsample_group_a, s=6.975)
bantusubsample_group_b <- tibble(family = "Bantu_subset", calibration = "b", tip = bantusubsample_group_b, s=4.458)
bantusubsample_group_c <- tibble(family = "Bantu_subset", calibration = "c", tip = bantusubsample_group_c, s=3.234)
bantusubsample_group_d <- tibble(family = "Bantu_subset", calibration = "d", tip = bantusubsample_group_d, s=2.498)


# Bantu subsample2 --------------------------------------------------------------------------------------------

bantusubsample2_group_a = c("Fefe_Grassfields",
                            "Kom_Grassfields",
                            "Mungaka_Grassfields",
                            "Oku_Grassfields",
                            "Moghamo_Grassfields")

bantusubsample2_group_b = c("A75a_Fang_Bitam" ,
                            "A86c_Mpiemo" ,
                            "A62A_Nuasue" ,
                            "B22b_Koya" ,
                            "B252_Mahongwe" ,
                            "A84_Njem" ,
                            "A62B_Mmala" ,
                            "B204_Ndambomo_Massoukou" ,
                            "A75a_Fang_Medouneu" ,
                            "B11b_Orungu" ,
                            "D11_Mbole" ,
                            "D33_Nyali" ,
                            "C83_Bushong" ,
                            "C25_Mboshi" ,
                            "D333_Ndaaka" ,
                            "D211_Kango" ,
                            "D334_Mbo" ,
                            "*D308_Ebodo" ,
                            "C24_Koyo" ,
                            "C323_Mpama" ,
                            "H16_Kimbeko" ,
                            "H16h_Kinkanu_2012" ,
                            "B501_Wanzi_E" ,
                            "B53_Tsaangi_Poungi" ,
                            "H16_Cimbala" ,
                            "H16g_Kimpangu_2012" ,
                            "B861_Ngul" ,
                            "B71a_Teke_Dj" ,
                            "B78_Wuumu" ,
                            "H16a_Kisikongo_2013" ,
                            "M42_Bemba" ,
                            "M61_Lenje" ,
                            "M64_Tonga" ,
                            "G24_Bondei" ,
                            "L13_Kwese" ,
                            "M62_Soli" ,
                            "L31a_Luba-Kasai" ,
                            "H41_Mbala" ,
                            "F24_Kimbu" ,
                            "F12_Bende" ,
                            "R21_Kwanyama" ,
                            "L33_Luba-Shaba" ,
                            "R31_Herero" ,
                            "L32_Kanyok" ,
                            "L23_Songe" ,
                            "K31_Luyana" ,
                            "L11_Pende")

bantusubsample2_group_c = c("A75a_Fang_Bitam",
                            "A62A_Nuasue",
                            "A62B_Mmala",
                            "A75a_Fang_Medouneu")

bantusubsample2_group_d = c("M42_Bemba",
                            "M61_Lenje",
                            "M64_Tonga",
                            "G24_Bondei",
                            "L13_Kwese",
                            "M62_Soli",
                            "H41_Mbala",
                            "F24_Kimbu",
                            "F12_Bende")

bantusubsample2_group_a <- tibble(family = "Bantu_subset2", calibration = "a", tip = bantusubsample2_group_a, s=6.975)
bantusubsample2_group_b <- tibble(family = "Bantu_subset2", calibration = "b", tip = bantusubsample2_group_b, s=4.458)
bantusubsample2_group_c <- tibble(family = "Bantu_subset2", calibration = "c", tip = bantusubsample2_group_c, s=3.234)
bantusubsample2_group_d <- tibble(family = "Bantu_subset2", calibration = "d", tip = bantusubsample2_group_d, s=2.498)

# Sino-tibetain ---------------------------------------------------------------------------------------------

group_sinitic = c("SiniticBeijing" ,
  "SiniticChaozhou" ,
  "SiniticGuangzhou" ,
  "SiniticJieyang" ,
  "SiniticLonggang" ,
  "SiniticXingning" )

st_group_sinitic <- tibble(family = "ST", calibration = "sinitic", tip = group_sinitic, s=2.076)

# TEA --------------------------------------------------------------------------------------------------------------------

tea_group_japonic = c("Japanese",
  "Old_Japanese",
  "Amami_Yamatohama",
  "Amami_Asama",
  "Amami_Yoron",
  "Okinawa_Yonamine",
  "Okinawa_Shuri",
  "Miyako_Irabu",
  "Yaeyama_Ishigaki",
  "Yaeyama_Hatoma",
  "Yonaguni",
  "Kagoshima",
  "Koshiki_islands",
  "Kumamoto",
  "Fukuoka",
  "Hachijo")

tea_group_koreanic = c("Hwanghae",
  "Southern_Hamgyong",
  "Northern_Hamgyong",
  "Southern_Pyongan",
  "Northern_Pyongan",
  "Jeju",
  "Southern_Jeolla",
  "Northern_Jeolla",
  "Southern_Gyeongsang",
  "Northern_Gyeongsang",
  "Southern_Chungcheong",
  "Northern_Chungcheong",
  "Gyeonggi",
  "Gangwon")

tea_group_turkic = c("BarabaTatar",
  "CodexCumanicus",
  "NorthAltai",
  "OldTurkic",
  "SouthAltai",
  "Azeri",
  "Bashkir",
  "Chuvash",
  "CrimeanTatar",
  "Dolgan",
  "Gagauz",
  "KaraKalpak",
  "KarachayBalkar",
  "Karaim",
  "Kazakh",
  "Khakas",
  "Khalaj",
  "Kirghiz",
  "Kumyk",
  "MiddleChulym",
  "Nogai",
  "Salar",
  "WestYugur",
  "Shor",
  "KazanTatar",
  "Tofa",
  "Turkish",
  "Turkmen",
  "Tuvan",
  "Uyghur",
  "Uzbek",
  "Yakut")

tea_group_mongolian = 
  c("Khalkha",
    "Buriat",
  "Kalmyck",
  "Oirat",
  "Kamnigan",
  "Dagur",
  "Shira-Yughur",
  "Baoan",
  "Dongxian",
  "Minhe",
  "Huzhu",
  "Kangjia",
  "Moghol",
  "Middle_Mongolian_Secret_History",
  "Middle_Mongolian_Muqaddimat_al-adab")

tea_group_tungusic = c("Hezhe",
                       "Oroch",
                       "Udihe",
                       "Nanai_Middle_Amur",
                       "Kur-Urmi",
                       "Nanai_Bikin",
                       "Orok",
                       "Ulcha",
                       "Jurchen",
                       "Manchu",
                       "Xibe",
                       "Even",
                       "Solon",
                       "Evenki_Kamnigan",
                       "Evenki_PT",
                       "Southern_Evenki_Chiringda",
                       "Northern_Evenki_Tutonchany",
                       "Northern_Evenki_Tura",
                       "Negidal",
                       "Oroqen")

# Comppute age of mrca's 

remove_burnin = function(trees,burnin_rate){
  n = as.numeric(length(trees))
  return(trees[as.integer(n*burnin_rate):n])
}


path= here("data/real/tea_ctmc-strict-fbd-constrained/tea_ctmc-strict-fbd-constrained.trees")
trees = read.nexus(path)
trees = remove_burnin(trees,0.2)
M = length(trees)
tree = trees[[M]]


# Age of MRCA japonic 
mrca_japonic = getMRCA(tree,tea_group_japonic)
age_mrca_japonic = (distRoot(tree,1)[[1]] - distRoot(tree,mrca_japonic)[[1]])*0.1

# Age of MRCA koreanic
mrca_koreanic = getMRCA(tree,tea_group_koreanic)
age_mrca_koreanic = (distRoot(tree,1)[[1]] - distRoot(tree,mrca_koreanic)[[1]])*0.1


# Age of MRCA turkic
mrca_turkic = getMRCA(tree,tea_group_turkic)
age_mrca_turkic = (distRoot(tree,1)[[1]] - distRoot(tree,mrca_turkic)[[1]])*0.1

# Age of MRCA mongolian
mrca_mongolian = getMRCA(tree,tea_group_mongolian)
age_mrca_mongolian = (distRoot(tree,1)[[1]] - distRoot(tree,mrca_mongolian)[[1]])*0.1

# Age of MRCA tungusic
mrca_tungusic = getMRCA(tree,tea_group_tungusic)
age_mrca_tungusic = (distRoot(tree,1)[[1]] - distRoot(tree,mrca_tungusic)[[1]])*0.1


tea_group_japonic <- tibble(family = "TEA", calibration = "japonic", tip = tea_group_japonic, s = age_mrca_japonic)
tea_group_koreanic <- tibble(family = "TEA", calibration = "koreanic", tip = tea_group_koreanic, s= age_mrca_koreanic)
tea_group_turkic <- tibble(family = "TEA", calibration = "turkic", tip = tea_group_turkic, s= age_mrca_turkic)
tea_group_mongolian <- tibble(family = "TEA", calibration = "mongolian", tip = tea_group_mongolian, s=age_mrca_mongolian)
tea_group_tungusic <- tibble(family = "TEA", calibration = "tungusic", tip = tea_group_tungusic, s= age_mrca_tungusic)


calibration <- bind_rows(
  bantu_group_a, bantu_group_b, bantu_group_c, bantu_group_d,
  bantusubsample_group_a,bantusubsample_group_b,bantusubsample_group_c,bantusubsample_group_d,
  bantusubsample2_group_a,bantusubsample2_group_b,bantusubsample2_group_c,bantusubsample2_group_d,
  st_group_sinitic,
  tea_group_japonic,tea_group_koreanic,tea_group_mongolian,tea_group_tungusic,tea_group_turkic)


write.csv(calibration, here("output/results/calibration.csv"))

